/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JFrame;
import org.opensourcephysics.frames.FFTRealFrame;
import org.opensourcephysics.frames.PlotFrame;

public class Derivar extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Derivar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Derivar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.setName("txtLimInferior"); // NOI18N

        jTextField2.setName("txtLimInferior"); // NOI18N

        jLabel1.setText("Limite inferior");

        jLabel2.setText("Limite Superior");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Derivada Coseno", "Derivada Seno", "Cuadrados", "Raiz" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)))))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jButton1.getAccessibleContext().setAccessibleName("btnDerivar");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        

        
        graficar();
        //JOptionPane.showMessageDialog(null, valor1 + " " + valor2);
        
        
    }//GEN-LAST:event_jButton1ActionPerformed
 
     private void graficar1()
    {
        PlotFrame frame = new PlotFrame("position", "amplitude", "cal");
        frame.setSize(400,400);
        for (double x = -10, dx = 0.01; x < 0.1; x+=dx) {
            frame.append(2,x, Math.log(x));
        }
        
         frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setVisible(true);
        
    }
     
    private void graficar()
    {
  
        int limI =  Integer.parseInt(      this.jTextField2.getText());
        int limS = Integer.parseInt(    this.jTextField1.getText());
        
        if (limI >= limS)
        {
            JOptionPane.showMessageDialog(null, "Limites errados");
        }
        
       int n=limS-limI;
        int tipo = this.jComboBox1.getSelectedIndex();
        double[] x = valorx(limI, limS);
        double[] y = valory(limI, limS, tipo);
        
        PlotFrame frame = new PlotFrame("X", "Y", "Derivadas");
        frame.setSize(400,400);
        for (int i = 0; i < n; i++) {
            frame.append(2, x[i], y[i]);   
            frame.setLineColor(2, Color.black);
            frame.setConnected(rootPaneCheckingEnabled);
        }
        
        frame.setVisible(true);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

    }
    
    private double[] valory (int limI, int limS ,int tipoFuncion)
    {
        double res1,res2, h;
        double[] g = new double[limS-limI];
        
        int n=limS-limI;
        double[] x = valorx(limI, limS);
        
        for (int j = 0; j < n; j++) {
            h=1;
            res1 = f(x[j]+1 , tipoFuncion);
            res2 = f(x[j] , tipoFuncion);
            
            g[j] =  (res1-res2)/(h);
            
        }             
        
        return g;
    }
    
    
    ///Retorna el array de X
    private double[] valorx(int limI, int limS )
    {
        double x[] = new double[limS-limI];
        int pos = 0;
        for (double i = limI, dx=1; i <limS; i+=dx) {
            
            x[pos] =i;
            pos +=1;
        }
        
        return x;
        
    }
    
    private double f(double x, int tipoFuncion)
    {
        double res;
        if (tipoFuncion==0)//derivadad del coseno
            {
                res = derCos(x);
            }
            else if (tipoFuncion==1)//derivadad del coseno
            {
                res = derSen(x);
            }
            else if (tipoFuncion==2)//derivadad del cuadrado
            {
                res = derCuadrado(x);
            }
        else///derivada de la raiz
            {
                res = derRaiz(x);
            }
        return res;
    }
    
    ///Derivada del seno
    private double derCos(double x)
    {
        return Math.sin((x))*-1;
    }
    
    ///Derivada del coseno
    private double derSen(double x)
    {
        return Math.cos(x);
    }
    
    ///Derivada cuadrado
    private double derCuadrado(double x)
    {
        return (2 * x) + x;   
    }
    
    ///Derivada cuadrado
    private double derRaiz(double x)
    {
        return  (x/2)*-1;   
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Derivar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Derivar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Derivar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Derivar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Derivar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
